spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=true
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.MySQL5Dialect
    show-sql: true
logging:
  level:
    org.springframework: INFO
    by.netcracker: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
server:
  port: 8088